### PR TITLE
BUG: Fixed command node expiry

### PR DESCRIPTION
**Pull request by lassoan**
If there were no incoming nodes, OpenIGTLink commands were not expired (they kept waiting). It was because command query node expiry was only checked after some nodes were received.
Fixed by moving query node expiry check out of the input message processing loop.

Also added an error log to report when converter->MRMLToIGTL fails.

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you! Should I update the git hash in Slicer?

**Comment by tokjun** [comment]
Thanks for your fix. I'll update the git hash. I'm almost ready to submit a request.

**Comment by lassoan** [comment]
ok, thanks!

**Comment by tokjun** [comment]
https://github.com/Slicer/Slicer/pull/429

**Pull request merged**
