### PR TITLE
Add License file

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @leochan2009  @lassoan @fedorov

**Comment by fedorov** [comment]
@leochan2009 why would you want to use Slicer license?

It is Slicer-specific, it is non-standard, and it is very long to read and comprehend. I would recommend you consider MIT or 3-clause BSD instead. Just a suggestion. Maybe something you should discuss within the OpenIGTLink community.

Relevant discussions with pointers for the reference: 
* https://github.com/Radiomics/pyradiomics/issues/268
* https://github.com/QIICR/dcmqi/issues/274

cc: @tokjun @lassoan @openigtlink-admin

**Comment by leochan2009** [comment]
@fedorov , we plan to move the OpenIGTLinkIF module from slicer core to an extension. i think this is standard for all slicer extensions.

**Comment by leochan2009** [comment]
@fedorov , thanks for your information and the reference.
I didn't know that it is recommended to switch from Slicer license to MIT or 3-clause BSD license. 
I definitely will discuss this issue in the openigtlink community.

**Comment by leochan2009** [comment]
@fedorov ,

Also we are making a new OpenIGTLinkIF module at this repo:
https://github.com/openigtlink/SlicerOpenIGTLink
it is still using old Slicer license, we might also switch to the new license.

Best,
Longquan

**Comment by fedorov** [comment]
@leochan2009 I am not saying it is community recommendation to switch away from Slicer license. It is just something I personally recommend to consider. Some of the arguments why this makes sense are discussed in the issues I referenced. The ultimate decision lies with your community, I just wanted to mention this for your consideration.

**Comment by leochan2009** [comment]
@fedorov I see,  
It seems like dcmqi can be built as a standalone or Slicer extension. So it make more sense to switch to a BSD license or MIT license. For the OpenIGTLinkIF extension, it can only be built in Slicer.  I will discuss with Junichi and other people. Thanks for you precious suggestion!

Best,
Longquan

**Comment by jcfr** [comment]
Hi,

In picked the Slicer license because current files are associated with it.

If you contact all contributors , you should be able to change to an OSI
approved license (eg BSD, Apache or MIT)

**Comment by tokjun** [comment]
Thanks @fedorov for the suggestion. I would vote for the 3-clause BSD license, because it has been used for the OpenIGTLink library.

**Pull request merged**
